apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project3-nginx-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theseanchristopher/project3-app-config.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: project3-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

